CREATE TABLE medicamentos (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(100) ,
  laboratorio VARCHAR2(100),
  fecha_fabricacion TIMESTAMP(6),
  fecha_vencimiento TIMESTAMP(6),
  cantidad_stock NUMBER,
  valor_unitario NUMBER,
  estado NUMBER(1) DEFAULT 1
   PRIMARY KEY (id),
CONSTRAINT UK_medicamentos UNIQUE (nombre, laboratorio)
);

CREATE TABLE ventas (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  fecha TIMESTAMP(6),
  medicamento_id NUMBER,
  cantidad NUMBER,
  valor_unitario NUMBER(12,2),
  valor_total NUMBER(22,2),
  PRIMARY KEY (id),
  FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id)
);